---
title: "DATA COMPARISONS"
author: "Pat Dumandan"
date: "4/20/2021"
output: html_document
---
Compare how breeding phenology differs qualitatively between Sarah's script and my script

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(portalr)
library(ggplot2)
library(lubridate)
```

#### Pat's script

``` {r warning=FALSE, message=FALSE, include=FALSE}
#LOAD INDIVIDUAL LEVEL-DATA
Portal_data_indiv=summarize_individual_rodents(
  clean = TRUE,
  type = "Rodents",
  length = "all",
  unknowns = FALSE,
  time = "date",
  fillweight = FALSE,
  min_plots = 1,
  min_traps = 1,
  download_if_missing = TRUE,
  quiet = FALSE
)%>%filter(!is.na(sex),!(treatment=="spectabs"), !(year<1988), !(year>2014), plot %in%c(1, 2, 4, 8, 9, 11, 12, 14, 17, 22,3, 6, 13, 15, 18, 19, 20, 21))

#PB DATASET####

#males####

portal_male=Portal_data_indiv%>%filter(sex=="M") 
head(portal_male)

repro_male=portal_male%>%
  filter(testes==c("S", "M", "R"))

PB=repro_male%>%
  filter(species=="PB", wgt>=16)

#get count of reproductive males per month per year per trt
pb_dat=PB%>%
  group_by(month, year, treatment)%>%
  summarise(reproductive=n())

#get total observed abundance for MALES per month per year per trt
total_PB=portal_male%>%
  filter(species=="PB")%>%
  group_by(month,year, treatment)%>%
  summarise(abundance=n())

#calculate proportion
#this creates NAs for months when no reproductive male was recorded
total_proportion_pb_m=right_join(pb_dat, total_PB)%>%
  mutate(proportion=reproductive/abundance, sex="male")%>%
  arrange(proportion)

total_proportion_pb_m[is.na(total_proportion_pb_m)] <- 0 #set non-detects to 0

#females####

portal_female=Portal_data_indiv%>%filter(sex=="F") #49% of individuals are males
head(portal_male)

repro_female=portal_female%>%
  filter(vagina==c("S", "P", "B")| pregnant=="P" | nipples==c("R", "E", "B") | lactation=="L")

PBf=repro_female%>%
  filter(species=="PB", wgt >=21)

#get count of reproductive males per month per year per trt
pbf_dat=PBf%>%
  group_by(month, year, treatment)%>%
  summarise(reproductive=n())

#get total observed abundance for each species per month per year per trt
total_PBf=portal_female%>%
  filter(species=="PB")%>%
  group_by(month,year, treatment)%>%
  summarise(abundance=n())

#calculate proportion
#this creates NAs for months when no reproductive male was recorded
total_proportion_pb_f=right_join(pbf_dat, total_PBf)%>%
  mutate(proportion=reproductive/abundance, sex="female")%>%
  arrange(proportion)

total_proportion_pb_f[is.na(total_proportion_pb_f)] <- 0 #set non-detects to 0

#PP DATASET####

#males####
PP=repro_male%>%
  filter(species=="PP", wgt >=10)

#get count of reproductive males per month per year per trt
PP_dat=PP%>%
  group_by(month, year, treatment)%>%
  summarise(reproductive=n())

#get total observed abundance for MALES per month per year per trt
total_PP=portal_male%>%
  filter(species=="PP")%>%
  group_by(month,year, treatment)%>%
  summarise(abundance=n())

#calculate proportion
#this creates NAs for months when no reproductive male was recorded
total_proportion_pp_m=right_join(PP_dat, total_PP)%>%
  mutate(proportion=reproductive/abundance, sex="male")%>%
  arrange(proportion)

total_proportion_pp_m[is.na(total_proportion_pp_m)] <- 0 #set non-detects to 0

#females####

PPf=repro_female%>%
  filter(species=="PP", wgt >=12)

#get count of reproductive males per month per year per trt
PPf_dat=PPf%>%
  group_by(month, year, treatment)%>%
  summarise(reproductive=n())

#get total observed abundance for each species per month per year per trt
total_PPf=portal_female%>%
  filter(species=="PP")%>%
  group_by(month,year, treatment)%>%
  summarise(abundance=n())

#calculate proportion
#this creates NAs for months when no reproductive male was recorded
total_proportion_pp_f=right_join(PPf_dat, total_PPf)%>%
  mutate(proportion=reproductive/abundance, sex="female")%>%
  arrange(proportion)

total_proportion_pp_f[is.na(total_proportion_pp_f)] <- 0 #set non-detects to 0

#DM DATASET####

#males####

DM=repro_male%>%
  filter(species=="DM", wgt>=22)

#get count of reproductive males per month per year per trt
DM_dat=DM%>%
  group_by(month, year, treatment)%>%
  summarise(reproductive=n())

#get total observed abundance for MALES per month per year per trt
total_DM=portal_male%>%
  filter(species=="DM")%>%
  group_by(month,year, treatment)%>%
  summarise(abundance=n())

#calculate proportion
#this creates NAs for months when no reproductive male was recorded
total_proportion_dm_m=right_join(DM_dat, total_DM)%>%
  mutate(proportion=reproductive/abundance, sex="male")%>%
  arrange(proportion)

total_proportion_dm_m[is.na(total_proportion_dm_m)] <- 0 #set non-detects to 0

#females####

DMf=repro_female%>%
  filter(species=="DM", wgt >=27)

#get count of reproductive males per month per year per trt
DMf_dat=DMf%>%
  group_by(month, year, treatment)%>%
  summarise(reproductive=n())

#get total observed abundance for each species per month per year per trt
total_DMf=portal_female%>%
  filter(species=="DM")%>%
  group_by(month,year, treatment)%>%
  summarise(abundance=n())

#calculate proportion
#this creates NAs for months when no reproductive male was recorded
total_proportion_dm_f=right_join(DMf_dat, total_DMf)%>%
  mutate(proportion=reproductive/abundance, sex="female")%>%
  arrange(proportion)

total_proportion_dm_f[is.na(total_proportion_dm_f)] <- 0 #set non-detects to 0

#COMBINE SEX-SPECIFIC DATA FOR EACH SPECIES####
PB_all=rbind(total_proportion_pb_m, total_proportion_pb_f)
PB_all=as.data.frame(PB_all)%>%
  mutate(species="PB")

PP_all=rbind(total_proportion_pp_m, total_proportion_pp_f)
PP_all=as.data.frame(PP_all)%>%
  mutate(species="PP")

DM_all=rbind(total_proportion_dm_m, total_proportion_dm_f)
DM_all=as.data.frame(DM_all)%>%
  mutate(species="DM")

#combine PB, PP and DM datasets####
all_sp=rbind(PB_all, PP_all, DM_all)

#add ndvi and precip monthly data####

prod=ndvi(level="monthly", sensor="landsat", fill=TRUE)

prod2=prod%>%
  mutate(year=year(date), month=month(date))

ppt=weather(level="monthly", fill=TRUE)%>%select(year,month,precipitation)

all_prod=right_join(prod2,all_sp)
all_prod_ppt=right_join(ppt, all_prod)%>%filter(!is.na(precipitation), !is.na(ndvi))

#add biomass data####
bmass=biomass(path="repo", level="Plot", type="Rodents",
              clean=TRUE, plots="all", time="date", shape="crosstab")%>%
  mutate(month=month(censusdate), date=day(censusdate), year=year(censusdate))%>%
   filter(!(year<1988), !(year>2014), !(treatment=="spectabs"), plot%in%c(1, 2, 4, 8, 9, 11, 12, 14, 17, 22,3, 6, 13, 15, 18, 19, 20, 21))

DM_bmass=bmass%>%select(DM, plot, treatment, censusdate)%>%
  mutate(month=month(censusdate), date=day(censusdate), year=year(censusdate))%>%
  group_by(month, year, treatment)%>%
  summarise(bmass_DM=sum(DM))

PB_bmass=bmass%>%select(PB, plot, treatment, censusdate)%>%
  mutate(month=month(censusdate), date=day(censusdate), year=year(censusdate))%>%
  group_by(month, year, treatment)%>%
  summarise(bmass_PB=sum(PB))

PP_bmass=bmass%>%select(PP, plot, treatment, censusdate)%>%
  mutate(month=month(censusdate), date=day(censusdate), year=year(censusdate))%>%
  group_by(month, year, treatment)%>%
  summarise(bmass_PP=sum(PP))

all_bmass=left_join(all_prod_ppt, DM_bmass, by=c("month", "year", "treatment"))
all2_bmass=left_join(all_bmass, PB_bmass, by=c("month", "year", "treatment"))
all3_bmass=left_join(all2_bmass, PP_bmass, by=c("month", "year", "treatment"))%>%
  filter(!is.na(bmass_DM), !is.na(bmass_PB), !is.na(bmass_PP))

pb_plot=all3_bmass%>%filter(species=="PB")
pp_plot=all3_bmass%>%filter(species=="PP")
dm_plot=all3_bmass%>%filter(species=="DM")
```

```{r message=FALSE, echo=FALSE}
ggplot(pb_plot, aes(y=proportion, x=month, col=treatment)) +
  geom_point() +
  ylab("P(breeding)")+
  stat_smooth(method = 'gam', formula = y ~ s(x))+
  ggtitle("PB")+
  facet_wrap(~sex)+
  scale_x_discrete(name="month", limits=c("Jan", "Feb", "Mar", "Apr","May", "Jun",
                                          "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"))+
  theme(axis.text.x= element_text(angle = 90, vjust=0.5, hjust=1),
        panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))

ggplot(pp_plot, aes(y=proportion, x=month, col=treatment)) +
  geom_point() +
  ylab("P(breeding)")+
  stat_smooth(method = 'gam', formula = y ~ s(x))+
  ggtitle("PP")+
  facet_wrap(~sex)+
  scale_x_discrete(name="month", limits=c("Jan", "Feb", "Mar", "Apr","May", "Jun",
                                          "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"))+
  theme(axis.text.x= element_text(angle = 90, vjust=0.5, hjust=1),
        panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))

ggplot(dm_plot, aes(y=proportion, x=month, col=treatment)) +
  geom_point() +
  ylab("P(breeding)")+
  stat_smooth(method = 'gam', formula = y ~ s(x))+
  ggtitle("DM")+
  facet_wrap(~sex)+
  scale_x_discrete(name="month", limits=c("Jan", "Feb", "Mar", "Apr","May", "Jun",
                                          "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"))+
  theme(axis.text.x= element_text(angle = 90, vjust=0.5, hjust=1),
        panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))
```

#### Sarah's script

```{r include=FALSE}
# functions used for data cleaning####

id_unknowns <- function(dat, tag_col) {
  
  # give unique numbers to blank tags
  # note: these are 7 digit numbers, so they are longer than any other tag type
  # note: tag_col is the column number for tags (i.e., 18)
  
  unk = 1000000
  
  for (irow in 1:nrow(dat)) {
    
    tag = dat[irow, tag_col]
    unk = unk + 1
    
    if (rapportools::is.empty(tag)) {
      dat[irow, tag_col] = unk
    } else if (tag == '0') {
      dat[irow, tag_col] = unk
    }
  }
  
  return(dat)
  
}

starred_tags <- function(dat, tags, spp_col, tag_col) {
  
  # check for *, which indicates a new tag
  # tags with multiple rows are sorted by species, then checked for *
  # if a * exists, then each time it is given a new unique tag, that ends with "s" for "star" (from note2 column)
  # find tags that are 6 characters but are toe tags, not PIT tags
  
  tags_6 <-
    dat[nchar(dat$tag) >= 6, ] # tags with 6 or more characters
  no_PITtags <- tags_6 %>%
    filter(stringr::str_detect(tag, "[HIMNOPRSTUX]")) %>% # have characters not found in PIT tags
    filter(grepl('\\d{4}\\w{2}', tag)) %>% # have 4 digits followed by 2 characters (unlikely to be a PIT tag)
    select(tag)
  
  numcount = 1
  
  for (t in 1:length(tags)) {
    # only run on ear and toe tags, pit tags are very unlikely to be duplicated
    
    if (nchar(tags[t]) < 6 | tags[t] %in% no_PITtags$tag) {
      tmp <- which(dat$tag == tags[t])
      
      # if indiv was captured multiple times
      if (nrow(dat[tmp, ]) > 1) {
        # check num species recorded. If more than one, does data look OK if separated on species?
        spp_list = unique(dat[tmp, spp_col]) # num of species with that tag
        
        for (sp in 1:length(spp_list)) {
          tmp2 = which(dat$tag == tags[t] & dat$species == spp_list[sp])
          
          isnew = as.vector(dat[tmp2, ]$note2)
          
          if ("*" %in% isnew) {
            rowbreaks = which(isnew == "*", arr.ind = TRUE) # find rows where * indicates a new tag
            
            for (r in 1:length(rowbreaks)) {
              if (r == 1) {
                # GIVE an ID up to the first *
                newtag = paste(tags[t], numcount, "s", sep = "") #make a new tag to keep separate
                dat[tmp2, ][1:rowbreaks[r] - 1, tag_col] = newtag # dataframe with rows before the next star
                numcount = numcount + 1
                
                # AND an ID to everything after the first * (the loop should take care of the next set and so on)
                newtag = paste(tags[t], numcount, "s", sep = "") # make a new tag to keep separate
                dat[tmp2, ][rowbreaks[r]:nrow(dat[tmp2, ]), tag_col] = newtag # identifies this as different
                numcount = numcount + 1
              } else if (r > 1) {
                # GIVE an ID to everything after the next *
                newtag = paste(tags[t], numcount, "s", sep = "") # make a new tag to keep separate
                dat[tmp2, ][rowbreaks[r]:nrow(dat[tmp2, ]), tag_col] = newtag
                numcount = numcount + 1
              }
            }
          }
        }
      }
    }
  }
  
  return(dat)
  
}

is_dead <- function(dat, tags, spp_col, tag_col) {
  
  # checks note5 for "D", which indicated a dead rat.
  # by definition, all captures with the same tagID afterwards, must be a different individual
  # assign these captures with a new tag ID that ends with 'm' for 'mortality.
  
  numcount = 1
  
  for (t in 1:length(tags)) {
    tmp <- which(dat$tag == tags[t])
    
    # if indiv was captured multiple times
    if (nrow(dat[tmp, ]) > 1) {
      # check num species recorded. If more than one, does data look OK if separated on species?
      spp_list = unique(dat[tmp, spp_col])
      
      for (sp in 1:length(spp_list)) {
        tmp2 = which(dat$tag == tags[t] & dat$species == spp_list[sp])
        
        isdead = as.vector(dat[tmp2, ]$note5)
        
        if ("D" %in% isdead) {
          rowbreaks = which(isdead == "D", arr.ind = TRUE) # find rows where D indicates a dead individuals
          endrow = nrow(dat[tmp2, ])                        # number of rows w/ that tag and species code
          
          for (r in 1:length(rowbreaks)) {
            # length(rowbreaks) = number times D recorded
            if (r == 1) {
              # first row break for that tag
              if (rowbreaks[r] == endrow) {
                # only one time where the tag and species combo is recorded
                
                # GIVE an ID up to the first *
                newtag = paste(tags[t], numcount, "m", sep = "") # make a new tag to keep separate
                numrows = nrow(dat[tmp2, ][1:rowbreaks[r], ])
                newtagvector = as.vector(rep(newtag, numrows))
                dat[tmp2, ][1:rowbreaks[r], tag_col] = newtag
                numcount = numcount + 1
                
              } else {
                # if number of rows w/ combo is higher than 1
                
                # GIVE an ID up to the first *
                newtag = paste(tags[t], numcount, "m", sep = "") # make a new tag to keep separate
                numrows = nrow(dat[tmp2, ][1:rowbreaks[r], ])
                newtagvector = as.vector(rep(newtag, numrows))
                dat[tmp2, ][1:rowbreaks[r], tag_col] = newtag
                numcount = numcount + 1
                
                # AND an ID to everything after the first "D" (the loop should take care of the next set and so on)
                startrow = rowbreaks[r] + 1
                newtag = paste(tags[t], numcount, "m", sep = "") # make a new tag to keep separate
                numrows = nrow(dat[tmp2, ][(startrow:endrow), ])
                newtagvector = as.vector(rep(newtag, numrows))
                dat[tmp2, ][(startrow:endrow), tag_col] = newtag
                numcount = numcount + 1
                
              }
            } else if (r > 1) {
              # if this is not the first time a D is encountered for this tag
              if (rowbreaks[r] == endrow) {
                break
              } else {
                # GIVE an ID to everything after the next "D"
                startrow = rowbreaks[r] + 1
                newtag = paste(tags[t], numcount, "m", sep = "") # make a new tag to keep separate
                numrows = nrow(dat[tmp2, ][(startrow:endrow), ])
                newtagvector = as.vector(rep(newtag, numrows))
                dat[tmp2, ][(startrow:endrow), tag_col] = newtag
                numcount = numcount + 1
                
              }
            }
          }
        }
      }
    }
  }
  
  return(dat)
  
}



is_duplicate_tag <- function(dat, tags, spp_col, tag_col) {
  
  # check the min to max year for a given tag.
  # If > 4, considered suspicious
  # If multiple species, considered suspicious
  # If adequately resolved, given a new unique tag number, that ends with d for "duplicate"
  # returns a list with 2 elements [1] altered data, [2] flagged data
  
  numcount = 100
  flagged_rats = data.frame("tag" = 1,
                            "reason" = 1,
                            "occurrences" = 1)
  outcount = 0
  
  # find tags that are 6 characters but are toe tags, not PIT tags
  tags_6 <-
    dat[nchar(dat$tag) >= 6, ] # tags with 6 or more characters
  no_PITtags <- tags_6 %>%
    filter(stringr::str_detect(tag, "[HIMNOPRSTUX]")) %>% # have characters not found in PIT tags
    filter(grepl('\\d{4}\\w{2}', tag)) %>% # have 4 digits followed by 2 characters (unlikely to be a PIT tag)
    select(tag)
  
  all_tags <- c(tags, as.list(unlist(no_PITtags)))
  unique_tags <- unique(all_tags)
  
  for (t in 1:length(unique_tags)) {
    # only run on ear and toe tags, pit tags are very unlikely to be duplicated
    if (nchar(tags[t]) < 6 | tags[t] %in% no_PITtags$tag) {
      tmp <- which(dat$tag == tags[t])
      
      # if indiv was captured multiple times
      if (nrow(dat[tmp, ]) > 1) {
        # more than 3 years between recaptures? Rodents are short-lived.
        if (max(dat[tmp, 1]) - min(dat[tmp, 1]) >= 3) {
          # check num species recorded. If more than one, does data look OK if separated on species?
          spp_list = unique(dat[tmp, spp_col])
          
          for (sp in 1:length(spp_list)) {
            tmp2 = which(dat$tag == tags[t] & dat$species == spp_list[sp])
            
            # Check for duplicate tags in the same period and same species.
            # This likely indicates multiple individuals with the same tag.
            if (anyDuplicated(dat[tmp2, ]) > 0) {
              outcount = outcount + 1
              flagged_rats[outcount, ] <-
                c(tags[t], "sameprd", nrow(dat[tmp, ]))
            }
            
            # Dipodomys are long-lived. Raise the threshold for these indivs
            if (spp_list[sp] %in% list("DO", "DM", "DS")) {
              if (max(dat[tmp2, 1]) - min(dat[tmp2, 1]) < 5) {
                newtag = paste(tags[t], numcount, "d", sep = "") # make a new tag to keep separate
                dat[tmp2, tag_col] = newtag
                numcount = numcount + 1
              } else {
                outcount = outcount + 1
                flagged_rats[outcount, ] <-
                  c(tags[t], "year", nrow(dat[tmp, ]))
              }
            }
            
            # Other genera are very short-lived. Flag data if same individual appears to occur >= 3 years.
            else {
              if (max(dat[tmp2, 1]) - min(dat[tmp2, 1]) < 3) {
                newtag = paste(tags[t], numcount, "d", sep = "") # make a new tag to keep separate
                dat[tmp2, tag_col] = newtag
                numcount = numcount + 1
              } else {
                outcount = outcount + 1
                flagged_rats[outcount, ] <-
                  c(tags[t], "year", nrow(dat[tmp, ]))
              }
            }
          }
        }
      }
    }
  }
  
  info = list(data = dat, bad = flagged_rats)
  return (info)
  
}


same_period <- function(dat, tags){
  
  # multiple individuals with same tag captured in same period = questionable
  
  flagged_rats = data.frame("tag"=1, "reason"=1, "occurrences"=1)
  outcount = 0
  
  for (t in 1:length(tags)){
    tmp <- which(dat$tag == tags[t])
    
    if (nrow(dat[tmp,]) > 1){
      periods = unique(dat[tmp,]$period)
      for (p in 1:length(periods)){
        ptmp <- which(dat$tag == tags[t] & dat$period == periods[p])
        if (nrow(dat[ptmp,]) > 1){
          outcount = outcount + 1
          flagged_rats[outcount,] <- c(tags[t], "sameprd", nrow(dat[ptmp,]))
          break
        }
      }
    }
  }
  
  return (flagged_rats)
  
}

find_bad_data2 <- function(dat, tags, sex_col, spp_col) {
  
  # used in 'subsetDat' function
  # check for consistent sex and species, outputs flagged tags to check, 
  #     or to remove from study
  
  flagged_rats = data.frame("tag" = 1,
                            "reason" = 1,
                            "occurrences" = 1)
  outcount = 0
  
  for (t in 1:length(tags)) {
    tmp <- which(dat$tag == tags[t])
    
    if (nrow(dat[tmp, ]) > 1) {
      # if indiv was captured multiple times
      spp_list = dat[tmp, spp_col]
      spp = spp_list[1]
      for (s in 2:length(spp_list)) {
        # check for consistent species
        if (spp_list[s] != spp) {
          outcount = outcount + 1
          flagged_rats[outcount, ] <-
            c(tags[t], "spp", nrow(dat[tmp, ]))
          break
        }
      }
    }
  }
  
  return(flagged_rats)
  
}

subsetDat <- function(dataset){
  
  # function to subset out proper data 
  # will find bad data, then delete it from the dataset
  
  tags = as.character(unique(dataset$tag)) # get list of unique tags
  flags = find_bad_data2(dataset, tags, 10, 9)   # list of flagged data
  
  # first, mark all uncertain or unmarked sex as "U" for unknown
  #     and get rid of other weird typos in sex column
  dataset[which(dataset$sex %in% c("", "P", "Z")), 10] = "U" 
  
  # get rid of results where we don't know the species for sure
  badspptags = unique(flags[which(flags$reason == "spp"), 1])    
  dataset = dataset[-which(dataset$tag %in% badspptags),] 
  # delete rows where species is unsure
  
  return (dataset)
  
}
```

```{r message=FALSE, echo=FALSE}
require(dplyr)
####load cleaned individual-level data####
Portal_data=summarize_individual_rodents(
  clean = TRUE,
  type = "Rodents",
  length = "all",
  unknowns = FALSE,
  fillweight = FALSE,
  min_plots = 1,
  min_traps = 1,
  download_if_missing = TRUE,
  quiet = FALSE)%>%filter(!is.na(sex),!(treatment=="spectabs"), !(year<1988), !(year>2014), 
           plot %in%c(1, 2, 4, 8, 9, 11, 12, 14, 17, 22,3, 6, 13, 15, 18, 19, 20, 21))
#Note: 18 plots included based on Ellen's paper

#add note5 column to filter out dead indivs####

Portal_rodent=read.csv("./PortalData/Rodents/Portal_rodent.csv")
Portal_data_indiv=left_join(Portal_data, Portal_rodent)%>%
  select(period, month, day, year, treatment, plot, stake, species, sex, reprod, age, testes, vagina, pregnant, nipples, lactation, hfl, wgt,tag,note2, note5)

#assign tag IDs for untagged individuals (0 and NA in tag column)####

all_tag=id_unknowns(Portal_data_indiv, 19) 

#find and remove bad periods (periods with only one day of trapping)####

Portal_rodent_trapping= read.csv("./PortalData/Rodents/Portal_rodent_trapping.csv")
tdat=Portal_rodent_trapping%>%group_by(period)%>%summarise(count=sum(sampled))%>%arrange(count)
bad_periods <- filter(tdat, count < 20) #based on Sarah's code
bad_periods <- as.list(bad_periods$period)

Portal_no_badperiod=all_tag[-which(all_tag$period %in%bad_periods),]%>%
  mutate(tag=as.character(tag)) #necessary so function for starred and duplicate tags will not break

#check quality of tags####

#make sure that records with * in note2 are recognized as new individuals

tags = unique(Portal_no_badperiod$tag)
star_tags = starred_tags(dat=Portal_no_badperiod, tags=tags, spp_col=8, tag_col=19)

#locate dead individuals
tags=unique(star_tags$tag)
dead_dat=is_dead(dat=star_tags, tags=tags, spp_col=8, tag_col=19)

# locate records of duplicated tags
tags=unique(dead_dat$tag)
dup_dat= is_duplicate_tag(dat=dead_dat, tags=tags, spp_col=8, tag_col=19) #returns a list of 2
duptags = unique(dup_dat$bad$tag)
no_dup = dup_dat$data[-which(dup_dat$data$tag %in% duptags),] #delete rows flagged as duplicates without clear resolution

# identify records where multiple indivs share same tag in same period
tags = unique(no_dup$tag)
same = same_period(no_dup, tags)

#eliminate tags that appear more than once in the same period - questionable data
sametags = unique(same$tag)
Portal_no_same= no_dup[-which(no_dup$tag %in% sametags),]

# remove bad data

Portal_clean=subsetDat(Portal_no_same)
Portal_clean=as.data.frame(Portal_clean)
#MALE AND FEMALE DATASET

portal_male2=Portal_clean%>%filter(sex=="M") 

repro_male2=portal_male2%>%
  filter(testes==c("S", "M", "R"))

portal_female2=Portal_clean%>%filter(sex=="F") #49% of individuals are males

repro_female2=portal_female2%>%
  filter(vagina==c("S", "P", "B")| pregnant=="P" | nipples==c("R", "E", "B") | lactation=="L")

#PB MALE
PB2=repro_male2%>%
  filter(species=="PB", wgt>=18)

#get count of reproductive males per month per year per trt
pb_dat2=PB2%>%
  group_by(month, year, treatment)%>%
  summarise(reproductive=n())

#get total observed abundance for MALES per month per year per trt
total_pb_m2=portal_male2%>%
  filter(species=="PB")%>%
  group_by(month,year, treatment)%>%
  summarise(abundance=n())

#calculate proportion
#this creates NAs for months when no reproductive male was recorded
total_proportion_pb_m2=right_join(pb_dat2, total_pb_m2)%>%
  mutate(proportion=reproductive/abundance, sex="male")%>%
  arrange(proportion)

total_proportion_pb_m2[is.na(total_proportion_pb_m2)] <- 0 #set non-detects to 0

#PB FEMALE
PBf2=repro_female2%>%
  filter(species=="PB", wgt >=21)

#get count of reproductive males per month per year per trt
pbf_dat2=PBf2%>%
  group_by(month, year, treatment)%>%
  summarise(reproductive=n())

#get total observed abundance for each species per month per year per trt
total_pbf2=portal_female2%>%
  filter(species=="PB")%>%
  group_by(month,year, treatment)%>%
  summarise(abundance=n())

#calculate proportion
#this creates NAs for months when no reproductive male was recorded
total_proportion_pb_f2=right_join(pbf_dat2, total_pbf2)%>%
  mutate(proportion=reproductive/abundance, sex="female")%>%
  arrange(proportion)

total_proportion_pb_f2[is.na(total_proportion_pb_f2)] <- 0 #set non-detects to 0

#PP MALE
PP2=repro_male2%>%
  filter(species=="PP", wgt>=13)%>%
  arrange(wgt)

#get count of reproductive males per month per year per trt
PP_dat2=PP%>%
  group_by(month, year, treatment)%>%
  summarise(reproductive=n())

#get total observed abundance for MALES per month per year per trt
total_PP2=portal_male2%>%
  filter(species=="PP")%>%
  group_by(month,year, treatment)%>%
  summarise(abundance=n())

#calculate proportion
#this creates NAs for months when no reproductive male was recorded
total_proportion_pp_m2=right_join(PP_dat2, total_PP2)%>%
  mutate(proportion=reproductive/abundance, sex="male")%>%
  arrange(proportion)

total_proportion_pp_m2[is.na(total_proportion_pp_m2)] <- 0 #set non-detects to 0

PPf2=repro_female2%>%
  filter(species=="PP",  wgt >=12)%>%
  arrange(wgt)

#get count of reproductive males per month per year per trt
PPf_dat2=PPf2%>%
  group_by(month, year, treatment)%>%
  summarise(reproductive=n())

#get total observed abundance for each species per month per year per trt
total_PPf2=portal_female2%>%
  filter(species=="PP")%>%
  group_by(month,year, treatment)%>%
  summarise(abundance=n())

#calculate proportion
#this creates NAs for months when no reproductive male was recorded
total_proportion_pp_f2=right_join(PPf_dat2, total_PPf2)%>%
  mutate(proportion=reproductive/abundance, sex="female")%>%
  arrange(proportion)

total_proportion_pp_f2[is.na(total_proportion_pp_f2)] <- 0 #set non-detects to 0

#DM MALE
DM2=repro_male2%>%
  filter(species=="DM", wgt>=22)

#get count of reproductive males per month per year per trt
DM_dat2=DM2%>%
  group_by(month, year, treatment)%>%
  summarise(reproductive=n())

#get total observed abundance for MALES per month per year per trt
total_DM2=portal_male2%>%
  filter(species=="DM")%>%
  group_by(month,year, treatment)%>%
  summarise(abundance=n())

#calculate proportion
#this creates NAs for months when no reproductive male was recorded
total_proportion_dm_m2=right_join(DM_dat2, total_DM2)%>%
  mutate(proportion=reproductive/abundance, sex="male")%>%
  arrange(proportion)

total_proportion_dm_m2[is.na(total_proportion_dm_m2)] <- 0 #set non-detects to 0

#DM FEMALE
DMf2=repro_female2%>%
  filter(species=="DM", wgt>=27)%>%arrange(wgt)

#get count of reproductive males per month per year per trt
DMf_dat2=DMf2%>%
  group_by(month, year, treatment)%>%
  summarise(reproductive=n())

#get total observed abundance for each species per month per year per trt
total_DMf2=portal_female2%>%
  filter(species=="DM")%>%
  group_by(month,year, treatment)%>%
  summarise(abundance=n())

#calculate proportion
#this creates NAs for months when no reproductive male was recorded
total_proportion_dm_f2=right_join(DMf_dat2, total_DMf2)%>%
  mutate(proportion=reproductive/abundance, sex="female")%>%
  arrange(proportion)

total_proportion_dm_f2[is.na(total_proportion_dm_f2)] <- 0 #set non-detects to 0

#COMBINE SEX-SPECIFIC DATA FOR EACH SPECIES####
PB_all2=rbind(total_proportion_pb_m2, total_proportion_pb_f2)
PB_all2=as.data.frame(PB_all2)%>%
  mutate(species="PB")

PP_all2=rbind(total_proportion_pp_m2, total_proportion_pp_f2)
PP_all=as.data.frame(PP_all2)%>%
  mutate(species="PP")

DM_all2=rbind(total_proportion_dm_m2, total_proportion_dm_f2)
DM_all2=as.data.frame(DM_all2)%>%
  mutate(species="DM")

#combine PB, PP and DM datasets####
all_sp2=rbind(PB_all2, PP_all2, DM_all2)

pb_plot2=all_sp2%>%filter(species=="PB")
pp_plot2=all_sp2%>%filter(species=="PP")
dm_plot2=all_sp2%>%filter(species=="DM")

```

```{r message=FALSE, echo=FALSE}
ggplot(pb_plot2, aes(y=proportion, x=month, col=treatment)) +
  geom_point() +
  ylab("P(breeding)")+
  stat_smooth(method = 'gam', formula = y ~ s(x))+
  ggtitle("PB")+
  facet_wrap(~sex)+
  scale_x_discrete(name="month", limits=c("Jan", "Feb", "Mar", "Apr","May", "Jun",
                                          "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"))+
  theme(axis.text.x= element_text(angle = 90, vjust=0.5, hjust=1),
        panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))

ggplot(pp_plot2, aes(y=proportion, x=month, col=treatment)) +
  geom_point() +
  ylab("P(breeding)")+
  stat_smooth(method = 'gam', formula = y ~ s(x))+
  ggtitle("PP")+
  facet_wrap(~sex)+
  scale_x_discrete(name="month", limits=c("Jan", "Feb", "Mar", "Apr","May", "Jun",
                                          "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"))+
  theme(axis.text.x= element_text(angle = 90, vjust=0.5, hjust=1),
        panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))

ggplot(dm_plot2, aes(y=proportion, x=month, col=treatment)) +
  geom_point() +
  ylab("P(breeding)")+
  stat_smooth(method = 'gam', formula = y ~ s(x))+
  ggtitle("DM")+
  facet_wrap(~sex)+
  scale_x_discrete(name="month", limits=c("Jan", "Feb", "Mar", "Apr","May", "Jun",
                                          "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"))+
  theme(axis.text.x= element_text(angle = 90, vjust=0.5, hjust=1),
        panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))
```
